### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple

### ISSUE THREAD

**Issue by Cereal-Killa** [WereDev/Wu10Man#28]
![image](https://user-images.githubusercontent.com/25939765/91889702-a063c800-ec64-11ea-95d2-b04b61aa1a13.png)

`2020-09-01 15:03:55.2085 INFO Application starting
2020-09-01 15:03:55.2854 ERROR System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at Autofac.Util.TypeExtensions.IsGenericTypeDefinedBy(Type this, Type openGeneric)
   at Autofac.Features.Metadata.StronglyTypedMetaRegistrationSource.RegistrationsFor(Service service, Func`2 registrationAccessor)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.RegistrationsFor(Service service)
   at Autofac.Core.Registration.ComponentRegistry.RegistrationsFor(Service service)
   at Autofac.Builder.StartableManager.StartStartableComponents(IDictionary`2 properties, IComponentContext componentContext)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at WereDev.Utils.Wu10Man.App.RegisterDependencies()
   at WereDev.Utils.Wu10Man.App..ctor()
`

[2020-09-01.log](https://github.com/WereDev/Wu10Man/files/5158030/2020-09-01.log)

**Comment by englishextra** [comment]
Well I had win 10 1151 10586 and used the previous release (https://github.com/WereDev/Wu10Man/releases/tag/v3.1.0) of wuman10 and had no errors, and I haven't tried latest release (https://github.com/WereDev/Wu10Man/releases/tag/v4.1.0) on that very first version of win10.

**Comment by Cereal-Killa** [comment]
> Well I had win 10 1151 10586 and used the previous release (https://github.com/WereDev/Wu10Man/releases/tag/v3.1.0) of wu10man and had no errors, and I haven't tried latest release (https://github.com/WereDev/Wu10Man/releases/tag/v4.1.0) on that very first version of win10.
> 
> So maybe you try the v3.1.0?

Correct, 3.1.0 does work.

I loaded up the project and installed System.ValueTuple from nuget, that solved the issue!

Even though you target .NET 4.6.1 there's most likely a nuget extension that references System.ValueTuple from .Net 4.7, it's my guess.

![LOQdVNk1P3](https://user-images.githubusercontent.com/25939765/91990034-9e067a00-ed07-11ea-9883-d50f170dacfe.png)

**Comment by Cereal-Killa** [comment]
Just in case: https://github.com/WereDev/Wu10Man/pull/29

**Comment by englishextra** [comment]
@Cereal-Killa Thanks for letting know that 3.1.0 works on win 10 1511.

I believe @WereDev is to get over this issue

**Comment by WereDev** [comment]
Hey, thanks for letting me know about this issue.  I'll take a look at this and see if adding an additional NuGet reference is appropriate.  I'd like to reduce the number of dependencies if possible.  I didn't realize that there might be an issue between 4.6.1 and 4.7.x given the build instructions.  I'll see if I can find a way to avoid the issue.  If not, I guess I'm adding a new reference.

**Comment by WereDev** [comment]
Looks like this was a result of updating the AutoFac dependency.  I'm removing AutoFac as a DI framework is probably a bit overkill for this app and replacing it with a more manual solution.  It also removes two dependencies as opposed to adding a new one.

I'm working on a few other things as well but should hopefully have an update out soon.

**Comment by WereDev** [comment]
Ok, release 4.2.0 is done.  Let me know if this fixes the issue for you.

https://github.com/WereDev/Wu10Man/releases/tag/v4.2.0

**Comment by Cereal-Killa** [comment]
> Ok, release 4.2.0 is done. Let me know if this fixes the issue for you.
> 
> https://github.com/WereDev/Wu10Man/releases/tag/v4.2.0

Working perfectly now, thank you!
