### ISSUE TITLE
Error disabling Windows Module Installer

### ISSUE THREAD

**Issue by sobake** [WereDev/Wu10Man#36]
I get this error when disabling the Windows Modules Installer.

> 2020-12-29 07:42:06.9157 INFO Application ended
> 2020-12-29 07:42:10.3939 INFO Application starting
> 2020-12-29 07:42:10.4289 INFO Application version: v4.2.1.0
> 2020-12-29 07:42:10.4339 INFO Windows 10 Enterprise LTSC 2019 Version 1809 Build 17763.
> 2020-12-29 07:42:10.4339 INFO .Net Framework: 528049 / 4.8 or later
> 2020-12-29 07:42:10.4339 INFO Main window initializing.
> 2020-12-29 07:42:10.4789 INFO Main window initialized.
> 2020-12-29 07:42:10.5489 INFO Wu10Man initializing.
> 2020-12-29 07:42:10.5739 INFO Windows Services rendered.
> 2020-12-29 07:42:10.6889 INFO Application started
> 2020-12-29 07:42:12.1697 ERROR System.InvalidOperationException: Cannot stop TrustedInstaller service on computer '.'.
>    at System.ServiceProcess.ServiceController.Stop()
>    at WereDev.Utils.Wu10Man.Providers.WindowsServiceProvider.StopService()
>    at WereDev.Utils.Wu10Man.Providers.WindowsServiceProvider.TryDisableService()
>    at WereDev.Utils.Wu10Man.Core.Services.WindowsServiceManager.DisableService(String serviceName)
>    at WereDev.Utils.Wu10Man.UserControls.WindowsServicesControl.DisableService(String serviceName, String displayName)
>    at WereDev.Utils.Wu10Man.UserControls.WindowsServicesControl.ToggleService(Object sender, RoutedEventArgs e)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.Controls.Primitives.ButtonBase.OnClick()
>    at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 2020-12-29 07:42:12.1697 ERROR System.ComponentModel.Win32Exception: The requested control is not valid for this service
> 
> 2020-12-29 07:42:14.3534 INFO Application ended

**Comment by sobake** [comment]
UPDATE: Ok it seems to be resolved after it started working on its own after a few attempts.
